### ISSUE TITLE
Additional resources

### ISSUE THREAD

**Issue by westurner** [jdfreder/jupyter-pip#14]

**Comment by westurner** [comment]
- https://github.com/ipython/ipython/issues/5742 (thanks!)
- https://github.com/ipython/ipython/pull/4666#issuecomment-30290366 (~archiving utilized imports and dependencies in the .ipnb)

**Comment by westurner** [comment]
- https://github.com/ipython/ipython/pull/4673 ("ENH: %lsext magic and entry_points for ipython_extensions, ipython_exporters") ... is it possible to list which of these are installed (e.g. with the version_information or watermark extensions)?

**Comment by jdfreder** [comment]
Thanks for the additional info wes!  I'll try to parse through the conversations sometime in the next few days.  At a quick glance, it looks like I wasn't involved in the original conversations.

**Comment by westurner** [comment]
In #4673 there's an example of setuptools entry_points for registering IPython extensions (stevedore was also too much). IDK how easy it would be to add that. Thanks again!

**Comment by jdfreder** [comment]
> setuptools entry_points

We are actually thinking about using entry_points for the upstream implementation, in Jupyter.

**Comment by westurner** [comment]
Outstanding!

**Comment by westurner** [comment]
Here's the branch I had started: https://github.com/ipython/ipython/compare/master...westurner:setuptools_entry_points
