### ISSUE TITLE
Detect when user=True should be passed to install_nbextension

### ISSUE THREAD

**Issue by rgbkrk** [jdfreder/jupyter-pip#7]
With non-root installations (where the user asks to do local install, etc.), `user` needs to be set to `True` in the call to `install_nbextension`.

Suggested by @carreau in https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/jupyter/YfeORebzBnk/ps4ql2Kvv9EJ

**Comment by jdfreder** [comment]
Taking a look...

**Comment by jdfreder** [comment]
@rgbkrk I pushed v0.3 to PYPI which addresses this.  Let me know how it works for you!
